# Generated by Django 2.1.7 on 2019-03-06 04:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BooleanField(default=False)),
                ('rightcnt', models.IntegerField(default=0)),
                ('set', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('set', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=5)),
                ('example1', models.CharField(max_length=50)),
                ('example2', models.CharField(max_length=50)),
                ('example3', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
    ]
