# Generated by Django 2.1.7 on 2019-02-17 15:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excl', models.TextField()),
                ('qu', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.IntegerField()),
                ('example1', models.CharField(max_length=50)),
                ('example2', models.CharField(max_length=50)),
                ('example3', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
    ]
